### ISSUE TITLE
On Windows 11: ModuleNotFoundError: No module named 'matplotlib.backends.backend_qt4agg' 

### ISSUE THREAD

**Issue by RFNajera** [ePublicHealth/GeoPublicHealth#10]
Students having an issue installing the plug-in on Windows 11 are having this same error:

ModuleNotFoundError: No module named 'matplotlib.backends.backend_qt4agg' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Lindsay Salem/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoPublicHealth\__init__.py", line 23, in 
    from GeoPublicHealth.src.plugin import GeoPublicHealthPlugin
  File "C:\PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Lindsay Salem/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoPublicHealth\src\plugin.py", line 32, in 
    from GeoPublicHealth.src.gui.main_window import MainDialog
  File "C:\PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Lindsay Salem/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoPublicHealth\src\gui\main_window.py", line 54, in 
    from GeoPublicHealth.src.gui.analysis.stats_dialog import StatsWidget
  File "C:\PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Lindsay Salem/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoPublicHealth\src\gui\analysis\stats_dialog.py", line 30, in 
    from matplotlib.backends.backend_qt4agg import \
  File "C:\PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'matplotlib.backends.backend_qt4agg'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.16.16-Hannover Hannover, f5778a89 
Python Path:
•	C:/PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python
•	C:/Users/Lindsay Salem/AppData/Roaming/QGIS/QGIS3\profiles\default/python
•	C:/Users/Lindsay Salem/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
•	C:/PROGRA~1/QGIS31~1.16/apps/qgis-ltr/./python/plugins
•	C:\Program Files\QGIS 3.16.16\bin\python39.zip
•	C:\PROGRA~1\QGIS31~1.16\apps\Python39\DLLs
•	C:\PROGRA~1\QGIS31~1.16\apps\Python39\lib
•	C:\Program Files\QGIS 3.16.16\bin
•	C:\Users\Lindsay Salem\AppData\Roaming\Python\Python39\site-packages
•	C:\PROGRA~1\QGIS31~1.16\apps\Python39
•	C:\PROGRA~1\QGIS31~1.16\apps\Python39\lib\site-packages
•	C:\PROGRA~1\QGIS31~1.16\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
•	C:\PROGRA~1\QGIS31~1.16\apps\Python39\lib\site-packages\win32
•	C:\PROGRA~1\QGIS31~1.16\apps\Python39\lib\site-packages\win32\lib
•	C:\PROGRA~1\QGIS31~1.16\apps\Python39\lib\site-packages\Pythonwin
•	C:/Users/Lindsay Salem/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by mvidaurre** [comment]
Check https://discourse.matplotlib.org/t/backend-qt4agg/19089/5 and https://sisteme-ig.com/questions/67064/error-de-instalacion-del-complemento-de-clasificacion-semiau

**Comment by mvidaurre** [comment]
Updated in this latest release
