### ISSUE TITLE
Couldn't Load GeoPublicHealth Plugin: AttributeError

### ISSUE THREAD

**Issue by kgarvey6** [ePublicHealth/GeoPublicHealth#7]
I am unable to Load the GeoPublicHealth Plugin on QGIS due to this error upon opening the QGIS app on my mac: "Couldn't Load GeoPublicHealth Plugin Attribute Error: module fiona has no attribute '_loading'"

Here is a screenshot of the error message that appears upon opening QGIS: 

<img width="910" alt="Couldn't Load Plugin error" src="https://user-images.githubusercontent.com/78385417/106548522-25d1f980-64dd-11eb-9f96-c2c4543ef5a0.png">

Here is the complete error message: 

Couldn't load plugin 'GeoPublicHealth' 
AttributeError: module 'fiona' has no attribute '_loading'

Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/kathleengarvey/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GeoPublicHealth/__init__.py", line 23, in 
    from GeoPublicHealth.src.plugin import GeoPublicHealthPlugin
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/kathleengarvey/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GeoPublicHealth/src/plugin.py", line 32, in 
    from GeoPublicHealth.src.gui.main_window import MainDialog
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/kathleengarvey/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GeoPublicHealth/src/gui/main_window.py", line 63, in 
    from GeoPublicHealth.src.gui.analysis.autocorrelation_dialog import (
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/kathleengarvey/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GeoPublicHealth/src/gui/analysis/autocorrelation_dialog.py", line 68, in 
    import pysal
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/pysal/__init__.py", line 3, in 
    from . import explore
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/pysal/explore/__init__.py", line 5, in 
    from . import spaghetti
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/pysal/explore/spaghetti/__init__.py", line 7, in 
    from .network import Network, PointPattern, SimulatedPointPattern
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/pysal/explore/spaghetti/network.py", line 7, in 
    from . import util
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/pysal/explore/spaghetti/util.py", line 8, in 
    import geopandas as gpd
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/geopandas/__init__.py", line 3, in 
    from geopandas.geoseries import GeoSeries  # noqa
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/geopandas/geoseries.py", line 10, in 
    from shapely.geometry.base import BaseGeometry
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/shapely/geometry/__init__.py", line 4, in 
    from .base import CAP_STYLE, JOIN_STYLE
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/shapely/geometry/base.py", line 18, in 
    from shapely.coords import CoordinateSequence
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/shapely/coords.py", line 8, in 
    from shapely.geos import lgeos
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/shapely/geos.py", line 23, in 
    import fiona
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/fiona/__init__.py", line 85, in 
    with fiona._loading.add_gdal_dll_directories():
AttributeError: module 'fiona' has no attribute '_loading'

Python version: 3.7.7 (default, Sep 22 2020, 10:25:18) [Clang 12.0.0 (clang-1200.0.32.2)] 
QGIS version: 3.16.3-Hannover Hannover, 3a90ea3afd 
Python Path:

/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/kathleengarvey/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/kathleengarvey/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/numba-0.50.1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/affine-2.3.0-py3.7.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/Pillow-7.2.0-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/Fiona-1.8.13.post1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/statsmodels-0.11.1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/click_plugins-1.1.1-py3.7.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/pandas-1.1.0-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/numpy-1.19.1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/patsy-0.5.1-py3.7.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/opencv_contrib_python-4.3.0.36-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/snuggs-1.4.7-py3.7.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/scipy-1.5.1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/Rtree-0.9.4-py3.7.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/geopandas-0.8.1-py3.7.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/matplotlib-3.3.0-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python37.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/pyproj-2.6.0-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/cftime-1.2.1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/netCDF4-1.5.3-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/GDAL-3.1.2-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/rasterio-1.1.5-py3.7-macosx-10.13.0-x86_64.egg
/Users/kathleengarvey/Library/Application Support/QGIS/QGIS3/profiles/default/python

My OS is OSX 11.1 and my QGIS Version is 3.16.

**Comment by mvidaurre** [comment]
@raynus do you have any idea, what can be the issue in this case?

**Comment by raynus** [comment]
@mvidaurre I think it's the fiona package.

Several user s on MacOS are having troubles getting this one install.

**Comment by mvidaurre** [comment]
Solved on the latest release
