### ISSUE TITLE
ModuleNotFoundError: No module named 'deprecated' 

### ISSUE THREAD

**Issue by isalles03** [ePublicHealth/GeoPublicHealth#8]
I am unable to Load the GeoPublicHealth Plugin on QGIS due to this error upon opening the QGIS app on my mac: getting this error ModuleNotFoundError: No module named 'deprecated' 

Troubleshooting:
Went into terminal ran pip3 install deprecated, gives me:
Requirement already satisfied: deprecated in /usr/local/lib/python3.9/site-packages (1.2.11)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.9/site-packages (from deprecated) (1.12.1)

Screenshot of error message (full text below):
<img width="1057" alt="Screen Shot 2021-02-12 at 4 29 04 PM" src="https://user-images.githubusercontent.com/78984855/107824538-a4d1f800-6d4f-11eb-8c65-d50340fa2126.png">
<img width="1343" alt="Screen Shot 2021-02-12 at 4 28 22 PM" src="https://user-images.githubusercontent.com/78984855/107824542-a6032500-6d4f-11eb-8a7c-51c1ac178743.png">

Full text:

Couldn't load plugin 'GeoPublicHealth' 

ModuleNotFoundError: No module named 'deprecated' 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/isadorasalles/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GeoPublicHealth/__init__.py", line 23, in 
    from GeoPublicHealth.src.plugin import GeoPublicHealthPlugin
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/isadorasalles/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GeoPublicHealth/src/plugin.py", line 32, in 
    from GeoPublicHealth.src.gui.main_window import MainDialog
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/isadorasalles/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GeoPublicHealth/src/gui/main_window.py", line 63, in 
    from GeoPublicHealth.src.gui.analysis.autocorrelation_dialog import (
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/isadorasalles/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GeoPublicHealth/src/gui/analysis/autocorrelation_dialog.py", line 68, in 
    import pysal
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/pysal/__init__.py", line 3, in 
    from . import explore
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/pysal/explore/__init__.py", line 2, in 
    from . import giddy
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/pysal/explore/giddy/__init__.py", line 12, in 
    from . import markov
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/pysal/explore/giddy/markov.py", line 19, in 
    import pysal.viz.mapclassify as mc
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/pysal/viz/__init__.py", line 1, in 
    from . import mapclassify
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/pysal/viz/mapclassify/__init__.py", line 4, in 
    from .classifiers import (
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/pysal/viz/mapclassify/classifiers.py", line 60, in 
    from deprecated import deprecated
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'deprecated'

Python version: 3.7.7 (default, Sep 22 2020, 10:25:18) [Clang 12.0.0 (clang-1200.0.32.2)] 
QGIS version: 3.16.3-Hannover Hannover, 3a90ea3afd 

Python Path:
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/isadorasalles/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/isadorasalles/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/rasterio-1.1.5-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python37.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/patsy-0.5.1-py3.7.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/numba-0.50.1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/affine-2.3.0-py3.7.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/geopandas-0.8.1-py3.7.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/opencv_contrib_python-4.3.0.36-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/netCDF4-1.5.3-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/click_plugins-1.1.1-py3.7.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/snuggs-1.4.7-py3.7.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/numpy-1.19.1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/Pillow-7.2.0-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/pyproj-2.6.0-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/statsmodels-0.11.1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/scipy-1.5.1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/GDAL-3.1.2-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/Rtree-0.9.4-py3.7.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/pandas-1.1.0-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/cftime-1.2.1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/Fiona-1.8.13.post1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/matplotlib-3.3.0-py3.7-macosx-10.13.0-x86_64.egg
/Users/isadorasalles/Library/Application Support/QGIS/QGIS3/profiles/default/python

Running macOS Catalina 10.15.7, QGIS 3.16

**Comment by taylormartinDO** [comment]
I am having the same issue, running on the same machine macOS Catalina 10.15.7, QGIS 3.16.

**Comment by mvidaurre** [comment]
Solved also in the latest release
